import test from 'node:test';import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';import path from 'node:path';
import {temporary,fingerprint} from './helpers.js';import {buildCapsule} from '../src/capsule.js';import {verifyCapsule} from '../src/verify.js';import {resumeOptions} from '../src/checkpoint.js';import {packCapsule,unpackCapsule,inspectArchive} from '../src/portable.js';
async function setup(t){const root=await temporary(t),repo=path.join(root,'repo');await mkdir(repo);await writeFile(path.join(repo,'app.cjs'),`const fs=require('node:fs');\nif(process.argv[2]==='good'){if(!fs.existsSync('required.txt'))throw new Error('GOOD_BROKEN');}\nelse {console.error('PAIRED_TARGET');process.exit(1);}\n`);await writeFile(path.join(repo,'required.txt'),'needed only by good');await writeFile(path.join(repo,'noise.txt'),'noise');return {root,repo,command:'node app.cjs bad',passingCommand:'node app.cjs good',matcher:{all:[{field:'exitCode',equals:1},{field:'stderr',contains:'PAIRED_TARGET'}]}};}
test('paired reduction rejects a broken good side, accepts harmless removal, verifies both after pack and rejects cache contamination',async t=>{
 const f=await setup(t),before=await fingerprint(f.repo),cacheDir=path.join(f.root,'cache');
 const single=await buildCapsule({...f,passingCommand:undefined,cacheDir,output:path.join(f.root,'single')});assert.ok(!single.manifest.retainedFiles.includes('required.txt'));
 const paired=await buildCapsule({...f,cacheDir,output:path.join(f.root,'paired')});assert.ok(paired.manifest.retainedFiles.includes('required.txt'));assert.ok(!paired.manifest.retainedFiles.includes('noise.txt'));assert.equal(paired.manifest.reduction.persistentCacheHits,0);assert.deepEqual(paired.verification.pairedVerification,{bad:'PASS',good:'PASS',passingExitCode:0});
 const archive=path.join(f.root,'case.rcap.gz');await packCapsule({capsule:paired.output,output:archive});assert.equal((await inspectArchive(archive)).pairedOracle.passingCommand,f.passingCommand);await unpackCapsule({archive,output:path.join(f.root,'fresh')});assert.equal((await verifyCapsule({capsule:path.join(f.root,'fresh')})).pairedVerification.good,'PASS');assert.equal(await fingerprint(f.repo),before);
 const m=JSON.parse(await readFile(path.join(paired.output,'capsule.json')));m.pairedOracle.passingCommand='node app.cjs bad';await writeFile(path.join(paired.output,'capsule.json'),JSON.stringify(m));await assert.rejects(verifyCapsule({capsule:paired.output}),{code:'CAPSULE_VERIFICATION_FAILED'});
});
test('paired budget and checkpoint restore policy and recheck both sides',async t=>{
 const f=await setup(t),checkpoint=path.join(f.root,'checkpoint.json');const p=await buildCapsule({...f,checkpoint,maxRuns:10,output:path.join(f.root,'partial')});assert.ok(p.manifest.reduction.reproductionAttempts<=10);const restored=await resumeOptions(checkpoint);assert.equal(restored.passingCommand,f.passingCommand);await assert.rejects(buildCapsule({...restored,passingCommand:undefined,output:path.join(f.root,'wrong')}),{code:'CHECKPOINT_INCOMPATIBLE'});const r=await buildCapsule({...restored,output:path.join(f.root,'resumed')});assert.ok(r.manifest.retainedFiles.includes('required.txt'));assert.equal(r.verification.pairedVerification.good,'PASS');
});
test('paired baseline refuses unrelated bad failure, eliminated target and nonpassing control',async t=>{
 const f=await setup(t);for(const [command,passingCommand] of [['node app.cjs good',f.passingCommand],['node absent.cjs',f.passingCommand],[f.command,'node app.cjs bad']])await assert.rejects(buildCapsule({...f,command,passingCommand,output:path.join(f.root,'invalid')}),{code:'INVALID_BASELINE'});
});
for(const changed of ['process.exit(0)','console.error("UNRELATED");process.exit(1)'])test(`paired candidate rejects changed bad outcome: ${changed}`,async t=>{
 const f=await setup(t);await writeFile(path.join(f.repo,'bad-required.txt'),'bad input');await writeFile(path.join(f.repo,'app.cjs'),`const fs=require('node:fs');if(process.argv[2]==='good')process.exit(0);if(!fs.existsSync('bad-required.txt')){${changed}}console.error('PAIRED_TARGET');process.exit(1);`);
 const r=await buildCapsule({...f,output:path.join(f.root,'paired')});assert.ok(r.manifest.retainedFiles.includes('bad-required.txt'));assert.equal(r.verification.pairedVerification.good,'PASS');
});
